name       : kholidays
version    : 5.54.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kholidays-5.54.0.tar.xz : 3e2c8eb4f094d8313cf340d7672a2f1f0c8f75c2d648d5eea06e620aedade6f6
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
