name       : kholidays
version    : 5.70.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/kholidays-5.70.0.tar.xz : 465c4903b58d5181e8fd63e8e9bdcdc12c7cf90a1a01884e999a88e943e92ee6
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
