name       : kholidays
version    : 5.57.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kholidays-5.57.0.tar.xz : f7db45906623c33dfbb297810082f8ff30c949e6a7d477f3b72de0521b0c9452
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
