name       : kholidays
version    : 5.89.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/kholidays-5.89.0.tar.xz : 1c956160ca1c45368b2f8a058224a4cb135f3d82759413ad3abbcbd9c6b1c067
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
