name       : kholidays
version    : 5.53.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kholidays-5.53.0.tar.xz : e512b0772c845042d9a0fd93d9f92c1705791b07849e84092b8f93bd6240c5fe
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
