name       : kholidays
version    : 5.46.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kholidays-5.46.0.tar.xz : d8936430384039368b6ec2ee06f8910ec73c3a6f109320f0802a661b7f19ab83
license    : LGPL-2.1
component  : desktop.library
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
