name       : kholidays
version    : 5.51.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kholidays-5.51.0.tar.xz : ba2c901dccc1c23cfadfd6cb05843ae47ffa5bc9f0cc432e61dccbb1e699755a
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
