name       : kholidays
version    : 5.62.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kholidays-5.62.0.tar.xz : f9f7cc399b35cef9348b8fbaabb87145b689165a66b874e3250456f6bbdcb329
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
