name       : kholidays
version    : 5.44.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kholidays-5.44.0.tar.xz : 22a0951cbd2a73eb332f76d6f71fcbbc770aeb0d530987017c2640caa6ed9f8c
license    : LGPL-2.1
component  : desktop.library
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
