name       : kholidays
version    : 17.12.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kholidays-17.12.2.tar.xz : 73ad92fc2f454124bc226e6e5b6701215c4fa70cc682edc94b69161f655dc256
license    : LGPL-2.1
component  : desktop.library
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
