name       : kholidays
version    : 5.77.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kholidays-5.77.0.tar.xz : 076862b69b38d9f8bde71f2f3b083da113a38ea419143c20f5186a1065b70552
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
