name       : kholidays
version    : 5.79.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kholidays-5.79.0.tar.xz : 16298163d85a27232b90f185b26741748a70222c191e557182cecd1ebcc16bd1
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
