name       : kholidays
version    : 5.75.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kholidays-5.75.0.tar.xz : 2ff86514a1165c88fc81b47476c5671b5e840633d3bf04cfe513881e4a0db7e5
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
optimize   : lto
summary    : KDE library for regional holiday information
description: |
    This library provides a C++ API that determines holiday and other special events for a geographical region.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
